### ISSUE TITLE
Recipes Box Text No Wrapped

### ISSUE THREAD

**Issue by pyetrosafe** [nvs/gem#455] opened 2019-06-26 02:29 UTC
The correct text in this box should separate each name from each tower per line!
I came back to play now, and I find it difficult to read these recipes with this wrong line break!
Thanks...

![WC3ScrnShot_062519_231226_01 - Copy](https://user-images.githubusercontent.com/5269715/60146623-a6c4fd00-97a0-11e9-9005-0b5b2eacfc65.png)

**Comment by nvs** [comment] 2019-06-26 07:26
This is a known issue, and is being fixed in 1.6. Just another carry over from the original Gem, where a lot of spaces were used instead of a line break. It aligns properly in 4:3 resolution, but no one plays that much anymore.

**Comment by pyetrosafe** [comment] 2019-06-27 04:40
Ah ok ... Hehehehe !!!
Just, let me ask ... The current setup, would be that difficulty in the original Bks Gem TD?
Would it be possible to add the initial configuration box, with the possibility of choosing the difficulties? Maybe just by changing the hitpoints of monsters and their armor ...
Another thing, would it be possible to also implement this initial configuration box, the ultimate boss hit points? Example: 2kk, 6kk and 10kk ... I liked to play version 3.1.6 which was 6kk the hit points of the last boss!
And finally, already being annoying, sorry, make a button to improve the hit rate of Extra Chances? ...

I would like to be able to help with the development, I will try to save some time and try to help. I need to learn the programming for the game maps, I'm a programmer but I never tried to create a map ^^ !!!

**Comment by nvs** [comment] 2019-06-30 08:17
Ah, I noticed you asked the same questions on the Discord. I'll paste my response from there here.

>Other difficulties were removed a while back. There are no plans to introduce different difficulties. This was to streamline the start process and prevent 'incorrect' options being forced on players, as well as making it easier to balance..
>
>As far as configurable options, that is something that will be introduced down the line. Players will be able to do this individually, along with being able to restart.
>
>And regarding the boss, the design is being changed in 1.6. But, there is little value in having it have more life. No strategy outside of utilizing Ancients can kill it in its pre-1.6 design. Increasing this is pointless as a challenge.
>
>And I'm not sure what you mean in regards to Extra Chance. It was reworked in Gem TD+ 1.5. It is being slightly adjusted in 1.6.

That being said, Ancients are probably still needed in 1.6. Eventually there will be competing strategies (and probably more Ancient nerfs).

**Comment by nvs** [comment] 2019-07-14 06:20
Closing this as a duplicate of #23. If you have other concerns, do voice them at the Discord or open another ticket.

As a side matter, the old Extra Chance could be improved via gold. As of 1.5 that is no longer necessary. Think of 1.5 as giving players free gold as Extra Chance no longer needs to be improved to be utilized fully. It is strictly superior to the old Extra Chance, and just improves as you use it if the bonus grows; albeit, it does have some of its own quirks. Those are being addressed in 1.6, as I mentioned previously.

**Closed as completed by nvs** 2019-07-14 06:20 UTC
