### ISSUE TITLE
Losing connection/desync

### ISSUE THREAD

**Issue by RandomPickNewb** [nvs/gem#152] opened 2016-07-23 22:09 UTC
There seems to be some problem with losing connection/desync at the start of the map.It sometimes happens it sometimes doesnt.
http://storage.entgaming.net/replay/view_replay.php?file=8089207.w3g
http://storage.entgaming.net/replay/view_replay.php?file=8089176.w3g
Idk if this is map related or host related but it only happens on the new version of gem td.

**Comment by nvs** [comment] 2016-07-24 01:28
@RandomPickNewb (player `randompicknewb`), I see [here](https://entgaming.net/findreplay.php?player=randompicknewb@server.eurobattle.net) that it looks like you played Trolls and Elves before the Gem games. Am I correct to make that assumption that you did not restart Warcraft 3 after your Trolls and Elves maps? If so, it is possible that this may be the culprit behind your desyncs. If you could let me know, that would be great.

Regardless, if you plan to play Gem please restart Warcraft 3 after any other maps. If you still run into desync issues, then that definitely means there could be an issue with Gem TD+. The reason I say do this is because some maps are protected/optimized with methods that end up poisoning Warcraft 3's cache (Gem TD+ is not one of these maps). This lasts until it is restarted. I'm not saying a map you played did this; I'm simply saying it is possible.

As for the player `fir.zecke[` (see [here](https://entgaming.net/findreplay.php?player=fir.zecke[)), it seems he a history of disconnecting on map start in the older versions of Gem, so I don't think his problem is isolated to this version of the map. I'm not ruling out an issue that has carried over from the old version of Gem due to a large sharing of the code base still. However, his disconnects are clustered, so I'd imagine internet issues.

**Comment by RandomPickNewb** [comment] 2016-07-24 17:18
Joined some more games with restarted war3/without it restarted and there were no desyncs so it was probably a problem on my end.

**Comment by nvs** [comment] 2016-07-24 18:36
If you continue to run into desyncs, let me know. I'll leave this issue open for a while, and if I hear nothing (good news!) then I'll close it. Thanks for the update.

**Comment by nvs** [comment] 2016-07-31 21:31
Closing this as no more issues have been reported, and it was most likely a problem caused by another map in the same Warcraft 3 session.

**Closed as completed by nvs** 2016-07-31 21:31 UTC
Labels: bug
